<?php

namespace AppBundle\Repository;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCalendrierByAnnonceAndData($annonce, $date)
    {
        $qb = $this->createQueryBuilder('ca');
        $expression = $qb->expr();
        $query = $qb
        ->where($expression->andx($expression->eq('ca.dateStatus', '?1'), $expression->eq('ca.annonce', '?2')))
        ->setParameter(1, $date)
        ->setParameter(2, $annonce)
        ->getQuery();
        return $query;
    }
}
