<?php

namespace AppBundle\Repository;

/**
 * ChatDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
