<?php

namespace AppBundle\Repository;

/**
 * CommentairesAnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesAnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
}
