<?php

namespace AppBundle\Repository;

/**
 * DemandesAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDemandeByUserAndAnnonce($user, $annonce)
    {
        $qb = $this->createQueryBuilder('d');
        $expression = $qb->expr();
        $query = $qb
        ->where($expression->andx($expression->eq('d.locataire', '?1'), $expression->eq('d.annonce', '?2')))
        ->setParameter(1, $user)
        ->setParameter(2, $annonce)
        ->getQuery();
        return $query;
    }
    public function getDemandesAnnonceByLoueur($loueur)
    {
        $qb = $this->createQueryBuilder('d');
        $expression = $qb->expr();
        $query = $qb
        ->join('d.annonce', 'a', 'WITH', $expression->eq('a.loueur', '?1'))
        ->where($expression->neq('d.status', 3))
        ->setParameter(1, $loueur)
        ->orderBy('d.status', 'ASC')
        ->getQuery();
        return $query;
    }
    public function getDemandesAnnonceByLocataire($locataire)
    {
        $qb = $this->createQueryBuilder('d');
        $expression = $qb->expr();
        $query = $qb
        ->where($expression->eq('d.locataire', '?1'))
        ->setParameter(1, $locataire)
        ->getQuery();
        return $query;
    }
}
