<?php

namespace AppBundle\Repository;

/**
 * DemandesAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
