<?php

namespace AppBundle\Repository;

/**
 * DicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DicoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDicoByDicotype($pattern)
    {
        $qb = $this->createQueryBuilder('d');
        return $qb
      ->join('d.dicotype', 'dt', 'WITH', $qb->expr()->eq('dt.dicotypeLibelle', '?1'))
      ->setParameter(1, $pattern);
    }
}
