<?php

namespace AppBundle\Repository;

/**
 * MarqueVoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueVoitureRepository extends \Doctrine\ORM\EntityRepository
{
}
