<?php

namespace AppBundle\Repository;

/**
 * Marque_VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Marque_VoitureRepository extends \Doctrine\ORM\EntityRepository
{
}
