<?php

namespace AppBundle\Repository;

/**
 * Modele_VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Modele_VoitureRepository extends \Doctrine\ORM\EntityRepository
{
}
