<?php

namespace AppBundle\Repository;

/**
 * ModeleVoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleVoitureRepository extends \Doctrine\ORM\EntityRepository
{
}
