<?php

namespace AppBundle\Repository;

/**
 * PriceCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
