<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReservationsForLoueur($user)
    {
        $qb = $this->createQueryBuilder('r');
        $query = $qb->join('r.demandeAnnonce', 'd')
            ->join('d.annonce', 'an', 'WITH', $qb->expr()->eq('an.loueur', '?1'))
            ->addSelect('d')
            ->addSelect('an')
            ->setParameter(1, $user)
            ->getQuery();
        return $query;
    }
    public function getReservationsForLocataire($user)
    {
        $qb = $this->createQueryBuilder('r');
        $expr = $qb->expr();
        $query = $qb->join('r.demandeAnnonce', 'd', 'WITH', $expr->eq('d.locataire', '?1'))
            ->join('d.annonce', 'an')
            ->addSelect('d')
            ->addSelect('an')
            ->setParameter(1, $user)
            ->getQuery();
        return $query;
    }
}
