imports:
    - { resource: parameters.yml }
    - { resource: config.yml }
    - { resource: config_prod_secrets.php }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
framework:
    session:
        # set handler_id to null to use default session handler from php.ini (memcached)
        handler_id:  ~

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type: error_log
        console:
            type:  console
