alter_studio_co_rent_homepage:
    path:     /
    defaults: { _controller: AlterStudioCoRentBundle:Default:index }
alter_studio_co_rent_rent:
    path:     /jep-makinen-tende
    defaults: { _controller: AlterStudioCoRentBundle:RentCarWizard:index }
list_makinat:
    path:     /makinat
    defaults: { _controller: AlterStudioCoRentBundle:ListCar:index }
profile:
    path:     /profile
    defaults: { _controller: AlterStudioCoRentBundle:Profile:index }
profile_edit:
    path:     /profile/edit
    defaults: { _controller: AlterStudioCoRentBundle:Profile:info }
add_annonce:
    path:     /annonce/add
    defaults: { _controller: AlterStudioCoRentBundle:Annonce:add }
edit_annonce:
    path:      annonce/edit/{id}
    defaults:
        _controller: AlterStudioCoRentBundle:Annonce:edit
    requirements:
        id: \d+
view_annonce:
    path:      annonce/view/{id}
    defaults:
        _controller: AlterStudioCoRentBundle:ListCar:view
    requirements:
        id: \d+
delete_photo_annonce:
    path: /annonce/delete/photo
    defaults: { _controller: AlterStudioCoRentBundle:Annonce:deletePhoto }
price_car:
    path:     /jep-makinen-tende/price
    defaults: { _controller: AlterStudioCoRentBundle:RentCarWizard:getPrice}
    methods:  [POST]
demande_annonce:
    path:     /demande/annonce
    defaults: { _controller: AlterStudioCoRentBundle:ListCar:demande}
    methods:  [POST]
test:
    path:     /test
    defaults: { _controller: AlterStudioCoRentBundle:Test:add }
