services:
    app.admin.dico:
        class: AppBundle\Admin\DicoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Dico" }
        arguments:
            - ~
            - AppBundle\Entity\Dico
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
