services:
      appbundle.registration_listener:
              class: AppBundle\EventListener\RegistrationListener
              arguments: []
              tags:
                  - { name: kernel.event_subscriber }

      appbundle.login_entry_point:
              class: AppBundle\EventListener\LoginEntryPoint
              arguments: ['@router']
      app.form.registration:
              class: AppBundle\Form\RegistrationType
              tags:
                  - { name: form.type, alias: app_user_registration }
      app.form.profile:
              class: AppBundle\Form\UserType
              tags:
                  - { name: form.type, alias: appbundle_user }
